[package]
name = "m5stack-imu-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
esp32-hal = "0.16.0"
embedded-hal = "0.2.7"
mpu6050 = "0.1.6"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
